package uid

import "net/http"

type Operation int

const (
	Login Operation = iota
	Logout
	Group
	Ungroup
	Register
	Unregister
)

// Client is a simplified http.Client interface
type Client interface {
	Do(req *http.Request) (*http.Response, error)
}

// Monitor interface describes an entity capable of processing log activity generated by
// the UserID Builder. See package github.com/xhoms/panoslib/uid/memmonitor documentation for additional details
type Monitor interface {
	Log(op Operation, subject, value string, tout *uint)
}
